
import React, { useState, useEffect } from 'react';
import { 
  Plus, Search, Edit2, Trash2, ChevronLeft, MapPin, Loader2, 
  Building2, CheckCircle2, AlertTriangle, CreditCard, Info, Copy, Check, X,
  Phone, Mail, User, Briefcase, MoreHorizontal, ExternalLink, FileText
} from 'lucide-react';
import { Client } from '../types';
import { db } from '../services/supabase';

const Clients: React.FC = () => {
  const [clients, setClients] = useState<Client[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [showModal, setShowModal] = useState(false);
  const [editingClient, setEditingClient] = useState<Client | null>(null);
  const [isSearchingCnpj, setIsSearchingCnpj] = useState(false);
  const [activeSideTab, setActiveSideTab] = useState<'endereco' | 'cobranca'>('endereco');
  
  const [isLoading, setIsLoading] = useState(false);
  const [operationSuccess, setOperationSuccess] = useState(false);
  const [errorDetails, setErrorDetails] = useState<{message: string, raw?: string, sql?: string} | null>(null);
  const [isCopied, setIsCopied] = useState(false);

  const initialFormData: Partial<Client> = {
    name: '',
    razao_social: '',
    document: '',
    email: '',
    billing_email: '',
    phone: '',
    codigo_externo: '',
    endereco: '',
    observacao: '',
    observacao_interna: '',
    status: 'active'
  };

  const [formData, setFormData] = useState(initialFormData);

  useEffect(() => { loadClients(); }, []);

  const loadClients = async () => {
    setIsLoading(true);
    try {
      const data = await db.clients.getAll();
      setClients(data || []);
    } catch (e) {
      console.error("Erro ao carregar lista:", e);
    } finally {
      setIsLoading(false);
    }
  };

  const handleCnpjSearch = async () => {
    const rawValue = formData.document || '';
    const cleanCnpj = rawValue.replace(/\D/g, '');
    
    if (cleanCnpj.length !== 14) {
      alert("Digite um CNPJ válido com 14 dígitos.");
      return;
    }
    
    setIsSearchingCnpj(true);
    try {
      const res = await fetch(`https://brasilapi.com.br/api/cnpj/v1/${cleanCnpj}`);
      if (!res.ok) throw new Error("CNPJ não encontrado");
      const data = await res.json();
      
      const fullAddr = `${data.logradouro || ''}, ${data.numero || 'SN'} - ${data.bairro || ''}, ${data.municipio || ''}/${data.uf || ''} - CEP: ${data.cep || ''}`;
      
      setFormData(prev => ({
        ...prev,
        name: (data.nome_fantasia || data.razao_social || '').toUpperCase(),
        razao_social: (data.razao_social || '').toUpperCase(),
        document: cleanCnpj,
        endereco: fullAddr.toUpperCase(),
        email: data.email || prev.email,
        phone: data.ddd_telefone_1 || prev.phone
      }));
    } catch (e) { 
      alert("Não foi possível localizar este CNPJ automaticamente.");
    } finally { 
      setIsSearchingCnpj(false); 
    }
  };

  const handleSave = async () => {
    if (!formData.name || !formData.document) return alert("Nome e CNPJ são obrigatórios.");

    setIsLoading(true);
    setErrorDetails(null);
    
    try {
      const clientData = {
        ...formData,
        id: editingClient ? editingClient.id : undefined 
      };

      const result: any = await db.clients.save(clientData);
      
      if (result.error) {
        const msg = result.error.message || "";
        const code = result.error.code || "";
        
        console.error("Erro Supabase:", result.error);

        if (msg.includes('id') || msg.includes('dependency') || msg.includes('constraint')) {
          setErrorDetails({
            message: "Conflito de tipos ou dependências no banco de dados.",
            raw: msg,
            sql: "ALTER TABLE services DROP CONSTRAINT IF EXISTS services_client_id_fkey; ALTER TABLE equipment DROP CONSTRAINT IF EXISTS equipment_client_id_fkey; ALTER TABLE services ALTER COLUMN client_id TYPE BIGINT USING (CASE WHEN client_id ~ '^[0-9]+$' THEN client_id::BIGINT ELSE NULL END); ALTER TABLE equipment ALTER COLUMN client_id TYPE BIGINT USING (CASE WHEN client_id ~ '^[0-9]+$' THEN client_id::BIGINT ELSE NULL END); ALTER TABLE clients DROP COLUMN IF EXISTS id CASCADE; ALTER TABLE clients ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY; ALTER TABLE services ADD CONSTRAINT services_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL; ALTER TABLE equipment ADD CONSTRAINT equipment_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE; NOTIFY pgrst, 'reload schema';"
          });
        } else if (code === 'PGRST204' || msg.includes('column')) {
          setErrorDetails({
            message: "Faltam colunas na tabela 'clients'.",
            raw: msg,
            sql: "ALTER TABLE clients ADD COLUMN IF NOT EXISTS razao_social TEXT, ADD COLUMN IF NOT EXISTS email TEXT, ADD COLUMN IF NOT EXISTS billing_email TEXT, ADD COLUMN IF NOT EXISTS phone TEXT, ADD COLUMN IF NOT EXISTS codigo_externo TEXT, ADD COLUMN IF NOT EXISTS endereco TEXT, ADD COLUMN IF NOT EXISTS observacao TEXT, ADD COLUMN IF NOT EXISTS observacao_interna TEXT; NOTIFY pgrst, 'reload schema';"
          });
        } else {
          setErrorDetails({ 
            message: "Erro ao sincronizar dados.",
            raw: msg
          });
        }
      } else {
        setOperationSuccess(true);
        await loadClients();
        setTimeout(() => {
          setShowModal(false);
          setOperationSuccess(false);
        }, 1200);
      }
    } catch (e: any) {
      setErrorDetails({ message: "Falha de comunicação.", raw: e.message });
    } finally {
      setIsLoading(false);
    }
  };

  const copySql = () => {
    if (errorDetails?.sql) {
      navigator.clipboard.writeText(errorDetails.sql);
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 2000);
    }
  };

  const getMapUrl = (address: string) => {
    if (!address) return '';
    return `https://maps.google.com/maps?q=${encodeURIComponent(address)}&t=&z=15&ie=UTF8&iwloc=&output=embed`;
  };

  const filteredClients = clients.filter(c => 
    (c.name || '').toLowerCase().includes(searchTerm.toLowerCase()) || 
    (c.document || '').includes(searchTerm) ||
    (c.razao_social || '').toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="pb-20 relative text-left">
      <div className="space-y-8 animate-fadeIn">
        {/* Alerta de Erro Crítico */}
        {errorDetails && (
          <div className="fixed inset-0 z-[3000] bg-slate-900/90 backdrop-blur-xl flex items-center justify-center p-6">
            <div className="bg-white w-full max-w-2xl rounded-[3rem] p-12 shadow-2xl border border-red-100 animate-slideUp">
              <div className="flex items-center justify-between mb-8">
                 <div className="flex items-center space-x-4 text-red-500">
                    <AlertTriangle className="w-10 h-10" />
                    <h3 className="text-2xl font-black uppercase tracking-tight">Ação Necessária</h3>
                 </div>
                 <button onClick={() => setErrorDetails(null)} className="p-2 hover:bg-slate-100 rounded-full transition-colors"><X className="w-6 h-6" /></button>
              </div>
              
              <div className="space-y-6">
                <div className="bg-red-50 p-6 rounded-2xl border border-red-100">
                  <p className="text-sm text-red-800 font-bold mb-2">{errorDetails.message}</p>
                  <p className="text-[10px] font-mono text-red-500 opacity-70 break-all">{errorDetails.raw}</p>
                </div>
                
                {errorDetails.sql && (
                  <div className="bg-slate-900 p-8 rounded-3xl border border-slate-800">
                    <p className="text-[10px] font-black text-blue-400 uppercase tracking-widest mb-4">Executar este Script no Supabase:</p>
                    <code className="text-[11px] text-white font-mono block break-all leading-relaxed bg-black/40 p-5 rounded-2xl border border-white/5">{errorDetails.sql}</code>
                    <button onClick={copySql} className="mt-6 w-full flex items-center justify-center space-x-3 py-4 bg-white/5 hover:bg-white/10 text-[#74C044] rounded-2xl transition-all border border-white/10 group">
                      {isCopied ? <Check className="w-5 h-5" /> : <Copy className="w-5 h-5 group-hover:scale-110 transition-transform" />}
                      <span className="text-[10px] font-black uppercase tracking-widest">{isCopied ? 'Copiado!' : 'Copiar Script'}</span>
                    </button>
                  </div>
                )}
                
                <button onClick={() => setErrorDetails(null)} className="w-full bg-[#004282] text-white py-6 rounded-2xl font-black uppercase text-xs tracking-widest shadow-2xl active:scale-95 transition-all">
                  Entendi
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Cabeçalho */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div>
            <h2 className="text-4xl font-black text-[#004282] tracking-tighter uppercase">Clientes</h2>
            <p className="text-sm text-slate-400 font-medium italic mt-1">Gestão centralizada de parceiros e contratantes.</p>
          </div>
          <div className="flex items-center gap-3">
            <div className="relative">
              <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-300 w-5 h-5" />
              <input type="text" placeholder="Filtrar por nome, CNPJ ou razão..." className="h-[56px] w-full md:w-96 pl-12 pr-6 bg-white border border-slate-200 rounded-2xl text-sm outline-none focus:border-[#004282] shadow-sm transition-all font-semibold"
                value={searchTerm} onChange={e => setSearchTerm(e.target.value)} />
            </div>
            <button onClick={() => { setEditingClient(null); setFormData(initialFormData); setShowModal(true); }} className="h-[56px] bg-[#74C044] text-white px-10 rounded-2xl font-black text-[11px] uppercase tracking-widest flex items-center space-x-3 shadow-lg hover:bg-[#65a83b] transition-all transform active:scale-95">
              <Plus className="w-5 h-5" />
              <span>Adicionar Novo</span>
            </button>
          </div>
        </div>

        {/* Lista de Clientes (Formato Tabular) */}
        <div className="bg-white rounded-[2.5rem] border border-slate-100 shadow-xl overflow-hidden">
          <div className="overflow-x-auto no-scrollbar">
            <table className="w-full text-left border-collapse">
              <thead className="bg-slate-50 border-b border-slate-100">
                <tr className="text-[10px] font-black text-slate-400 uppercase tracking-widest">
                  <th className="px-8 py-6 w-16 text-center">Status</th>
                  <th className="px-8 py-6">Parceiro / Razão Social</th>
                  <th className="px-8 py-6">Identificação (CNPJ)</th>
                  <th className="px-8 py-6">Contato Direto</th>
                  <th className="px-8 py-6">Localização</th>
                  <th className="px-8 py-6 text-center">Ações</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-50">
                {filteredClients.length > 0 ? filteredClients.map((c) => (
                  <tr key={c.id} className="hover:bg-slate-50/80 transition-colors group cursor-pointer" onClick={() => { setEditingClient(c); setFormData(c); setShowModal(true); }}>
                    <td className="px-8 py-6 text-center">
                      <div className="flex items-center justify-center">
                        <div className={`w-3 h-3 rounded-full shadow-sm ${c.status === 'active' ? 'bg-[#74C044]' : 'bg-red-400'}`} title={c.status === 'active' ? 'Ativo' : 'Inativo'}></div>
                      </div>
                    </td>
                    <td className="px-8 py-6">
                      <div className="flex flex-col">
                        <span className="font-black text-slate-800 uppercase text-sm group-hover:text-[#004282] transition-colors line-clamp-1">{c.name}</span>
                        <span className="text-[10px] text-slate-400 font-bold uppercase truncate max-w-[200px]">{c.razao_social || '---'}</span>
                      </div>
                    </td>
                    <td className="px-8 py-6">
                      <div className="flex items-center space-x-2">
                         <Briefcase className="w-3.5 h-3.5 text-slate-300" />
                         <span className="text-xs font-black text-slate-600 tracking-wider font-mono">{c.document}</span>
                      </div>
                    </td>
                    <td className="px-8 py-6">
                      <div className="flex flex-col space-y-1">
                        <div className="flex items-center space-x-2 text-[11px] font-bold text-slate-500">
                          <Mail className="w-3 h-3 text-slate-300" />
                          <span className="truncate max-w-[150px]">{c.email || 'N/A'}</span>
                        </div>
                        <div className="flex items-center space-x-2 text-[11px] font-bold text-slate-500">
                          <Phone className="w-3 h-3 text-[#74C044]" />
                          <span>{c.phone || 'N/A'}</span>
                        </div>
                      </div>
                    </td>
                    <td className="px-8 py-6">
                      <div className="flex items-center space-x-2 max-w-[200px]">
                        <MapPin className="w-3.5 h-3.5 text-red-300 shrink-0" />
                        <span className="text-[11px] font-medium text-slate-500 italic line-clamp-1">{c.endereco || 'Endereço não definido'}</span>
                      </div>
                    </td>
                    <td className="px-8 py-6 text-center">
                      <div className="flex items-center justify-center space-x-2">
                        <button onClick={(e) => { e.stopPropagation(); setEditingClient(c); setFormData(c); setShowModal(true); }} className="p-3 bg-blue-50 text-[#004282] hover:bg-[#004282] hover:text-white rounded-xl transition-all shadow-sm transform active:scale-90" title="Editar">
                          <Edit2 className="w-4 h-4" />
                        </button>
                        <button onClick={async (e) => { 
                          e.stopPropagation(); 
                          if(confirm(`Deseja remover permanentemente ${c.name}?`)) { 
                            await db.clients.delete(c.id); 
                            loadClients(); 
                          } 
                        }} className="p-3 bg-red-50 text-red-400 hover:bg-red-500 hover:text-white rounded-xl transition-all shadow-sm transform active:scale-90" title="Excluir">
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </td>
                  </tr>
                )) : (
                  <tr>
                    <td colSpan={6} className="px-8 py-24 text-center">
                      <div className="flex flex-col items-center space-y-4 opacity-20">
                        <Building2 className="w-16 h-16 text-slate-300" />
                        <p className="font-black uppercase text-[10px] tracking-widest text-slate-400">Nenhum cliente localizado na base de dados.</p>
                      </div>
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
          <div className="px-8 py-4 bg-slate-50 border-t border-slate-100 flex items-center justify-between">
             <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{filteredClients.length} Registro(s) Encontrado(s)</span>
             <div className="flex space-x-2">
                <div className="w-2 h-2 rounded-full bg-[#74C044]"></div>
                <div className="w-2 h-2 rounded-full bg-slate-200"></div>
             </div>
          </div>
        </div>
      </div>

      {/* Modal Principal */}
      {showModal && (
        <div className="fixed inset-0 z-[1000] bg-slate-900/60 backdrop-blur-md overflow-y-auto p-4 md:p-10 animate-fadeIn">
          <div className="max-w-[1500px] mx-auto space-y-6 pb-20">
            
            <div className="bg-white p-8 rounded-[2.5rem] shadow-2xl flex flex-col md:flex-row items-center justify-between border border-slate-100 gap-6">
              <button onClick={() => setShowModal(false)} className="flex items-center space-x-4 text-[#004282] text-2xl font-black uppercase tracking-tighter hover:opacity-70 transition-all">
                <ChevronLeft className="w-10 h-10" />
                <span>Ficha do Cliente</span>
              </button>
              <button onClick={handleSave} disabled={isLoading} className="w-full md:w-auto bg-[#004282] text-white px-16 py-6 rounded-3xl font-black uppercase text-xs tracking-widest shadow-2xl flex items-center justify-center space-x-4 active:scale-95 transition-all">
                {isLoading ? <Loader2 className="w-5 h-5 animate-spin text-[#74C044]" /> : <CheckCircle2 className="w-5 h-5 text-[#74C044]" />}
                <span>{editingClient ? 'Atualizar Dados' : 'Concluir Cadastro'}</span>
              </button>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
              
              <div className="lg:col-span-3 space-y-8">
                <div className="bg-white p-10 rounded-[3rem] shadow-sm border border-slate-100">
                  <h4 className="text-[10px] font-black text-[#004282] uppercase mb-6 flex items-center tracking-widest">
                    <Search className="w-3.5 h-3.5 mr-2" /> Consulta Rápida
                  </h4>
                  <div className="relative">
                    <input type="text" className="w-full bg-slate-50 border-none rounded-2xl px-6 py-5 text-sm font-bold text-slate-700 outline-none placeholder:text-slate-300"
                      placeholder="CNPJ para busca..."
                      value={formData.document} onChange={e => setFormData({...formData, document: e.target.value})} />
                    <button onClick={handleCnpjSearch} className="absolute right-3 top-1/2 -translate-y-1/2 p-3 bg-[#004282] text-white rounded-xl hover:bg-blue-900 transition-all">
                      {isSearchingCnpj ? <Loader2 className="w-5 h-5 animate-spin" /> : <Search className="w-5 h-5" />}
                    </button>
                  </div>
                </div>

                <div className="bg-white p-10 rounded-[3rem] shadow-sm border border-slate-100 space-y-8">
                  <h4 className="text-[10px] font-black text-slate-400 uppercase border-b pb-6 tracking-widest flex items-center">
                    <Building2 className="w-3.5 h-3.5 mr-2" /> Administrativo
                  </h4>
                  <div className="space-y-6">
                    <div className="space-y-2">
                       <label className="text-[9px] font-black text-slate-400 uppercase tracking-widest ml-1">Nome Fantasia *</label>
                       <input type="text" className="w-full border-b border-slate-100 py-3 text-sm font-bold text-slate-700 outline-none uppercase placeholder:text-slate-200"
                         placeholder="NOME CURTO"
                         value={formData.name} onChange={e => setFormData({...formData, name: e.target.value})} />
                    </div>
                    <div className="space-y-2">
                       <label className="text-[9px] font-black text-slate-400 uppercase tracking-widest ml-1">Razão Social</label>
                       <input type="text" className="w-full border-b border-slate-100 py-3 text-sm font-bold text-slate-700 outline-none uppercase placeholder:text-slate-200"
                         placeholder="RAZÃO COMPLETA"
                         value={formData.razao_social} onChange={e => setFormData({...formData, razao_social: e.target.value})} />
                    </div>
                    <div className="space-y-2">
                       <label className="text-[9px] font-black text-slate-400 uppercase tracking-widest ml-1">ID Externo</label>
                       <input type="text" className="w-full border-b border-slate-100 py-3 text-sm font-bold text-slate-700 outline-none uppercase placeholder:text-slate-200"
                         placeholder="CÓDIGO ERP"
                         value={formData.codigo_externo} onChange={e => setFormData({...formData, codigo_externo: e.target.value})} />
                    </div>
                    <div className="space-y-2">
                       <label className="text-[9px] font-black text-slate-400 uppercase tracking-widest ml-1">Status Base</label>
                       <select className="w-full border-b border-slate-100 py-3 text-sm font-black text-slate-700 outline-none appearance-none cursor-pointer"
                         value={formData.status} onChange={e => setFormData({...formData, status: e.target.value as any})}>
                         <option value="active">ATIVO NO SISTEMA</option>
                         <option value="inactive">INATIVO / BLOQUEADO</option>
                       </select>
                    </div>
                  </div>
                </div>
              </div>

              <div className="lg:col-span-5 bg-white p-12 rounded-[3.5rem] shadow-sm border border-slate-100 min-h-[600px]">
                <div className="flex border-b border-slate-50 mb-10">
                  <button className="px-8 py-5 text-[11px] font-black uppercase text-[#004282] border-b-4 border-[#004282] tracking-widest flex items-center">
                    <FileText className="w-4 h-4 mr-2" /> Prontuário & Observações
                  </button>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
                   <div className="space-y-4">
                      <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Documentação Técnica</label>
                      <textarea rows={15} className="w-full bg-slate-50 rounded-[2rem] p-8 text-sm outline-none border border-transparent focus:ring-4 focus:ring-[#004282]/5 font-medium placeholder:text-slate-300 leading-relaxed"
                        placeholder="Observações que constarão nos laudos técnicos e certificados de calibração..."
                        value={formData.observacao} onChange={e => setFormData({...formData, observacao: e.target.value})}></textarea>
                   </div>
                   <div className="space-y-4">
                      <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Histórico / Uso Interno</label>
                      <textarea rows={15} className="w-full bg-slate-50 rounded-[2rem] p-8 text-sm outline-none border border-transparent focus:ring-4 focus:ring-[#004282]/5 font-medium placeholder:text-slate-300 leading-relaxed"
                        placeholder="Informações estratégicas, histórico de relacionamento e controle interno Metrolab..."
                        value={formData.observacao_interna} onChange={e => setFormData({...formData, observacao_interna: e.target.value})}></textarea>
                   </div>
                </div>
              </div>

              <div className="lg:col-span-4 bg-white rounded-[3.5rem] shadow-sm border border-slate-100 overflow-hidden flex flex-col min-h-[600px]">
                <div className="flex bg-slate-50">
                   <button onClick={() => setActiveSideTab('endereco')} className={`flex-1 py-7 text-[10px] font-black uppercase tracking-[0.2em] transition-all ${activeSideTab === 'endereco' ? 'bg-white text-[#004282] border-b-4 border-[#004282]' : 'text-slate-400 hover:text-slate-600'}`}>
                    Logística
                   </button>
                   <button onClick={() => setActiveSideTab('cobranca')} className={`flex-1 py-7 text-[10px] font-black uppercase tracking-[0.2em] transition-all ${activeSideTab === 'cobranca' ? 'bg-white text-[#004282] border-b-4 border-[#004282]' : 'text-slate-400 hover:text-slate-600'}`}>
                    Faturamento
                   </button>
                </div>

                <div className="p-10 space-y-10 flex-1 flex flex-col">
                  {activeSideTab === 'endereco' ? (
                    <>
                      <div className="space-y-3">
                        <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Endereço de Atendimento</label>
                        <textarea rows={3} className="w-full bg-slate-50 border-none rounded-2xl px-6 py-4 text-sm font-bold text-slate-700 outline-none uppercase placeholder:text-slate-200"
                          placeholder="RUA, NÚMERO, BAIRRO, CIDADE/UF - CEP"
                          value={formData.endereco} onChange={e => setFormData({...formData, endereco: e.target.value.toUpperCase()})} />
                      </div>
                      <div className="flex-1 w-full bg-slate-100 rounded-[2.5rem] relative overflow-hidden border border-slate-200 shadow-inner group">
                         {formData.endereco ? (
                           <iframe title="Localização Google Maps" width="100%" height="100%" frameBorder="0" style={{ border: 0 }} src={getMapUrl(formData.endereco)} allowFullScreen className="opacity-90 group-hover:opacity-100 transition-opacity"></iframe>
                         ) : (
                           <div className="absolute inset-0 flex flex-col items-center justify-center text-slate-300">
                             <MapPin className="w-20 h-20 mb-6 opacity-20 animate-bounce" />
                             <span className="text-[11px] font-black uppercase tracking-widest text-slate-400">Aguardando endereço para mapa</span>
                           </div>
                         )}
                      </div>
                    </>
                  ) : (
                    <div className="space-y-8 animate-fadeIn">
                       <div className="space-y-3">
                          <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest flex items-center">
                            <CreditCard className="w-4 h-4 mr-2 text-[#74C044]" /> E-mail para Faturas
                          </label>
                          <input type="email" className="w-full bg-slate-50 border-none rounded-2xl px-6 py-5 font-bold text-slate-700 outline-none placeholder:text-slate-300"
                            placeholder="financeiro@empresa.com"
                            value={formData.billing_email} onChange={e => setFormData({...formData, billing_email: e.target.value})} />
                       </div>
                       <div className="space-y-3">
                          <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest flex items-center">
                            <Phone className="w-4 h-4 mr-2 text-[#74C044]" /> Central de Contato
                          </label>
                          <input type="text" className="w-full bg-slate-50 border-none rounded-2xl px-6 py-5 font-bold text-slate-700 outline-none placeholder:text-slate-300"
                            placeholder="(00) 00000-0000"
                            value={formData.phone} onChange={e => setFormData({...formData, phone: e.target.value})} />
                       </div>
                       <div className="space-y-3">
                          <label className="text-[10px] font-black text-slate-400 uppercase tracking-widest flex items-center">
                            <Mail className="w-4 h-4 mr-2 text-[#74C044]" /> E-mail Institucional
                          </label>
                          <input type="email" className="w-full bg-slate-50 border-none rounded-2xl px-6 py-5 font-bold text-slate-700 outline-none placeholder:text-slate-300"
                            placeholder="contato@empresa.com"
                            value={formData.email} onChange={e => setFormData({...formData, email: e.target.value})} />
                       </div>
                    </div>
                  )}
                </div>
              </div>

            </div>
          </div>
        </div>
      )}

      {operationSuccess && (
        <div className="fixed inset-0 z-[2000] bg-slate-900/50 backdrop-blur-lg flex items-center justify-center animate-fadeIn">
          <div className="bg-white p-16 rounded-[4rem] shadow-2xl text-center border border-green-50 animate-bounce">
             <div className="w-24 h-24 bg-green-50 rounded-full flex items-center justify-center mx-auto text-green-500 mb-8 shadow-inner">
                <CheckCircle2 className="w-12 h-12" />
             </div>
             <p className="font-black text-slate-800 text-2xl uppercase tracking-tighter">Dados Atualizados!</p>
          </div>
        </div>
      )}
    </div>
  );
};

export default Clients;
